### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by LorgeN** [LorgeN/EasyDB#1]
- [ ] Complete external tables
- [ ] Proxied managers
- [ ] Automated foreign keys for SQL
- [ ] Profiling of inherited classes (e. g. key-less extra data using keys from superclass)
- [ ] init.sql data structure generator for SQL
